/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated/prompts'
import { Route as AuthenticatedOrcamentoRouteImport } from './routes/_authenticated/orcamento'
import { Route as AuthenticatedMovimentosRouteImport } from './routes/_authenticated/movimentos'
import { Route as AuthenticatedImportarExtratosRouteImport } from './routes/_authenticated/importar-extratos'
import { Route as AuthenticatedContasRubricasRouteImport } from './routes/_authenticated/contas-rubricas'
import { Route as AuthenticatedCentrosCustoRouteImport } from './routes/_authenticated/centros-custo'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentoRoute = AuthenticatedOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentosRoute = AuthenticatedMovimentosRouteImport.update({
  id: '/movimentos',
  path: '/movimentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarExtratosRoute =
  AuthenticatedImportarExtratosRouteImport.update({
    id: '/importar-extratos',
    path: '/importar-extratos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasRubricasRoute =
  AuthenticatedContasRubricasRouteImport.update({
    id: '/contas-rubricas',
    path: '/contas-rubricas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCentrosCustoRoute =
  AuthenticatedCentrosCustoRouteImport.update({
    id: '/centros-custo',
    path: '/centros-custo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/centros-custo': typeof AuthenticatedCentrosCustoRoute
  '/contas-rubricas': typeof AuthenticatedContasRubricasRoute
  '/importar-extratos': typeof AuthenticatedImportarExtratosRoute
  '/movimentos': typeof AuthenticatedMovimentosRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/prompts': typeof AuthenticatedPromptsRoute
}
export interface FileRoutesByTo {
  '/aceitar-convite': typeof AceitarConviteRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/centros-custo': typeof AuthenticatedCentrosCustoRoute
  '/contas-rubricas': typeof AuthenticatedContasRubricasRoute
  '/importar-extratos': typeof AuthenticatedImportarExtratosRoute
  '/movimentos': typeof AuthenticatedMovimentosRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aceitar-convite': typeof AceitarConviteRoute
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/centros-custo': typeof AuthenticatedCentrosCustoRoute
  '/_authenticated/contas-rubricas': typeof AuthenticatedContasRubricasRoute
  '/_authenticated/importar-extratos': typeof AuthenticatedImportarExtratosRoute
  '/_authenticated/movimentos': typeof AuthenticatedMovimentosRoute
  '/_authenticated/orcamento': typeof AuthenticatedOrcamentoRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-convite'
    | '/auth'
    | '/admin'
    | '/centros-custo'
    | '/contas-rubricas'
    | '/importar-extratos'
    | '/movimentos'
    | '/orcamento'
    | '/prompts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/aceitar-convite'
    | '/auth'
    | '/admin'
    | '/centros-custo'
    | '/contas-rubricas'
    | '/importar-extratos'
    | '/movimentos'
    | '/orcamento'
    | '/prompts'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/aceitar-convite'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/centros-custo'
    | '/_authenticated/contas-rubricas'
    | '/_authenticated/importar-extratos'
    | '/_authenticated/movimentos'
    | '/_authenticated/orcamento'
    | '/_authenticated/prompts'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AceitarConviteRoute: typeof AceitarConviteRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamento': {
      id: '/_authenticated/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof AuthenticatedOrcamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentos': {
      id: '/_authenticated/movimentos'
      path: '/movimentos'
      fullPath: '/movimentos'
      preLoaderRoute: typeof AuthenticatedMovimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar-extratos': {
      id: '/_authenticated/importar-extratos'
      path: '/importar-extratos'
      fullPath: '/importar-extratos'
      preLoaderRoute: typeof AuthenticatedImportarExtratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas-rubricas': {
      id: '/_authenticated/contas-rubricas'
      path: '/contas-rubricas'
      fullPath: '/contas-rubricas'
      preLoaderRoute: typeof AuthenticatedContasRubricasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros-custo': {
      id: '/_authenticated/centros-custo'
      path: '/centros-custo'
      fullPath: '/centros-custo'
      preLoaderRoute: typeof AuthenticatedCentrosCustoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCentrosCustoRoute: typeof AuthenticatedCentrosCustoRoute
  AuthenticatedContasRubricasRoute: typeof AuthenticatedContasRubricasRoute
  AuthenticatedImportarExtratosRoute: typeof AuthenticatedImportarExtratosRoute
  AuthenticatedMovimentosRoute: typeof AuthenticatedMovimentosRoute
  AuthenticatedOrcamentoRoute: typeof AuthenticatedOrcamentoRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCentrosCustoRoute: AuthenticatedCentrosCustoRoute,
  AuthenticatedContasRubricasRoute: AuthenticatedContasRubricasRoute,
  AuthenticatedImportarExtratosRoute: AuthenticatedImportarExtratosRoute,
  AuthenticatedMovimentosRoute: AuthenticatedMovimentosRoute,
  AuthenticatedOrcamentoRoute: AuthenticatedOrcamentoRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AceitarConviteRoute: AceitarConviteRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
